#include "Keyboard.h"

namespace Genesis {
    std::string keyToString(Key key) {
        switch (key) {
            case Key::KEY_BACKSPACE:
                return "Key::KEY_BACKSPACE";
            case Key::KEY_ENTER:
                return "Key::KEY_ENTER";
            case Key::KEY_TAB:
                return "Key::KEY_TAB";

            case Key::KEY_PAUSE:
                return "Key::KEY_PAUSE";
            case Key::KEY_CAPITAL:
                return "Key::KEY_CAPITAL";

            case Key::KEY_ESCAPE:
                return "Key::KEY_ESCAPE";

            case Key::KEY_MODECHANGE:
                return "Key::KEY_MODECHANGE";

            case Key::KEY_SPACE:
                return "Key::KEY_SPACE";
            case Key::KEY_PAGEUP:
                return "Key::KEY_PAGEUP";
            case Key::KEY_PAGEDOWN:
                return "Key::KEY_PAGEDOWN";
            case Key::KEY_END:
                return "Key::KEY_END";
            case Key::KEY_HOME:
                return "Key::KEY_HOME";
            case Key::KEY_LEFT:
                return "Key::KEY_LEFT";
            case Key::KEY_UP:
                return "Key::KEY_UP";
            case Key::KEY_RIGHT:
                return "Key::KEY_RIGHT";
            case Key::KEY_DOWN:
                return "Key::KEY_DOWN";
            case Key::KEY_SELECT:
                return "Key::KEY_SELECT";
            case Key::KEY_PRINT:
                return "Key::KEY_PRINT";
            case Key::KEY_EXECUTE:
                return "Key::KEY_EXECUTE";
            case Key::KEY_INSERT:
                return "Key::KEY_INSERT";
            case Key::KEY_DELETE:
                return "Key::KEY_DELETE";
            case Key::KEY_HELP:
                return "Key::KEY_HELP";

            case Key::KEY_LSUPER:
                return "Key::KEY_LSUPER";
            case Key::KEY_RSUPER:
                return "Key::KEY_RSUPER";
            case Key::KEY_MENU:
                return "Key::KEY_MENU";

            case Key::KEY_NUMPAD0:
                return "Key::KEY_NUMPAD0";
            case Key::KEY_NUMPAD1:
                return "Key::KEY_NUMPAD1";
            case Key::KEY_NUMPAD2:
                return "Key::KEY_NUMPAD2";
            case Key::KEY_NUMPAD3:
                return "Key::KEY_NUMPAD3";
            case Key::KEY_NUMPAD4:
                return "Key::KEY_NUMPAD4";
            case Key::KEY_NUMPAD5:
                return "Key::KEY_NUMPAD5";
            case Key::KEY_NUMPAD6:
                return "Key::KEY_NUMPAD6";
            case Key::KEY_NUMPAD7:
                return "Key::KEY_NUMPAD7";
            case Key::KEY_NUMPAD8:
                return "Key::KEY_NUMPAD8";
            case Key::KEY_NUMPAD9:
                return "Key::KEY_NUMPAD9";
            case Key::KEY_MULTIPLY:
                return "Key::KEY_MULTIPLY";
            case Key::KEY_ADD:
                return "Key::KEY_ADD";
            case Key::KEY_SEPARATOR:
                return "Key::KEY_SEPARATOR";
            case Key::KEY_SUBTRACT:
                return "Key::KEY_SUBTRACT";
            case Key::KEY_DECIMAL:
                return "Key::KEY_DECIMAL";
            case Key::KEY_DIVIDE:
                return "Key::KEY_DIVIDE";
            case Key::KEY_F1:
                return "Key::KEY_F1";
            case Key::KEY_F2:
                return "Key::KEY_F2";
            case Key::KEY_F3:
                return "Key::KEY_F3";
            case Key::KEY_F4:
                return "Key::KEY_F4";
            case Key::KEY_F5:
                return "Key::KEY_F5";
            case Key::KEY_F6:
                return "Key::KEY_F6";
            case Key::KEY_F7:
                return "Key::KEY_F7";
            case Key::KEY_F8:
                return "Key::KEY_F8";
            case Key::KEY_F9:
                return "Key::KEY_F9";
            case Key::KEY_F10:
                return "Key::KEY_F10";
            case Key::KEY_F11:
                return "Key::KEY_F11";
            case Key::KEY_F12:
                return "Key::KEY_F12";
            case Key::KEY_F13:
                return "Key::KEY_F13";
            case Key::KEY_F14:
                return "Key::KEY_F14";
            case Key::KEY_F15:
                return "Key::KEY_F15";
            case Key::KEY_F16:
                return "Key::KEY_F16";
            case Key::KEY_F17:
                return "Key::KEY_F17";
            case Key::KEY_F18:
                return "Key::KEY_F18";
            case Key::KEY_F19:
                return "Key::KEY_F19";
            case Key::KEY_F20:
                return "Key::KEY_F20";
            case Key::KEY_F21:
                return "Key::KEY_F21";
            case Key::KEY_F22:
                return "Key::KEY_F22";
            case Key::KEY_F23:
                return "Key::KEY_F23";
            case Key::KEY_F24:
                return "Key::KEY_F24";

            case Key::KEY_NUMLOCK:
                return "Key::KEY_NUMLOCK";
            case Key::KEY_SCROLL:
                return "Key::KEY_SCROLL";

            case Key::KEY_NUMPAD_EQUAL:
                return "Key::KEY_NUMPAD_EQUAL";

            case Key::KEY_LSHIFT:
                return "Key::KEY_LSHIFT";
            case Key::KEY_RSHIFT:
                return "Key::KEY_RSHIFT";
            case Key::KEY_LCONTROL:
                return "Key::KEY_LCONTROL";
            case Key::KEY_RCONTROL:
                return "Key::KEY_RCONTROL";
            case Key::KEY_LALT:
                return "Key::KEY_LALT";
            case Key::KEY_RALT:
                return "Key::KEY_RALT";

            case Key::KEY_SEMICOLON:
                return "Key::KEY_SEMICOLON";
            case Key::KEY_APOSTROPHE:
                return "Key::KEY_APOSTROPHE";
            case Key::KEY_EQUAL:
                return "Key::KEY_EQUAL";
            case Key::KEY_COMMA:
                return "Key::KEY_COMMA";
            case Key::KEY_MINUS:
                return "Key::KEY_MINUS";
            case Key::KEY_PERIOD:
                return "Key::KEY_PERIOD";
            case Key::KEY_SLASH:
                return "Key::KEY_SLASH";
            case Key::KEY_GRAVE:
                return "Key::KEY_GRAVE";

            case Key::KEY_0:
                return "Key::KEY_0";
            case Key::KEY_1:
                return "Key::KEY_1";
            case Key::KEY_2:
                return "Key::KEY_2";
            case Key::KEY_3:
                return "Key::KEY_3";
            case Key::KEY_4:
                return "Key::KEY_4";
            case Key::KEY_5:
                return "Key::KEY_5";
            case Key::KEY_6:
                return "Key::KEY_6";
            case Key::KEY_7:
                return "Key::KEY_7";
            case Key::KEY_8:
                return "Key::KEY_8";
            case Key::KEY_9:
                return "Key::KEY_9";

            case Key::KEY_A:
                return "Key::KEY_A";
            case Key::KEY_B:
                return "Key::KEY_B";
            case Key::KEY_C:
                return "Key::KEY_C";
            case Key::KEY_D:
                return "Key::KEY_D";
            case Key::KEY_E:
                return "Key::KEY_E";
            case Key::KEY_F:
                return "Key::KEY_F";
            case Key::KEY_G:
                return "Key::KEY_G";
            case Key::KEY_H:
                return "Key::KEY_H";
            case Key::KEY_I:
                return "Key::KEY_I";
            case Key::KEY_J:
                return "Key::KEY_J";
            case Key::KEY_K:
                return "Key::KEY_K";
            case Key::KEY_L:
                return "Key::KEY_L";
            case Key::KEY_M:
                return "Key::KEY_M";
            case Key::KEY_N:
                return "Key::KEY_N";
            case Key::KEY_O:
                return "Key::KEY_O";
            case Key::KEY_P:
                return "Key::KEY_P";
            case Key::KEY_Q:
                return "Key::KEY_Q";
            case Key::KEY_R:
                return "Key::KEY_R";
            case Key::KEY_S:
                return "Key::KEY_S";
            case Key::KEY_T:
                return "Key::KEY_T";
            case Key::KEY_U:
                return "Key::KEY_U";
            case Key::KEY_V:
                return "Key::KEY_V";
            case Key::KEY_W:
                return "Key::KEY_W";
            case Key::KEY_X:
                return "Key::KEY_X";
            case Key::KEY_Y:
                return "Key::KEY_Y";
            case Key::KEY_Z:
                return "Key::KEY_Z";

            case Key::KEY_LBRACKET:
                return "Key::KEY_LBRACKET";
            case Key::KEY_BACKSLASH:
                return "Key::KEY_BACKSLASH";
            case Key::KEY_RBRACKET:
                return "Key::KEY_RBRACKET";

            default:
                return "Unknown Key";
        }
    }
}  // namespace Genesis
